package com.test.entity;

import com.test.entity.SystemUsersRole;
import com.test.entity.SystemUsersRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SystemUsersRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_USERS_ROLE
     *
     * @mbggenerated Thu Mar 29 16:21:41 GMT+08:00 2012
     */
    int countByExample(SystemUsersRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_USERS_ROLE
     *
     * @mbggenerated Thu Mar 29 16:21:41 GMT+08:00 2012
     */
    int deleteByExample(SystemUsersRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_USERS_ROLE
     *
     * @mbggenerated Thu Mar 29 16:21:41 GMT+08:00 2012
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_USERS_ROLE
     *
     * @mbggenerated Thu Mar 29 16:21:41 GMT+08:00 2012
     */
    int insert(SystemUsersRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_USERS_ROLE
     *
     * @mbggenerated Thu Mar 29 16:21:41 GMT+08:00 2012
     */
    int insertSelective(SystemUsersRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_USERS_ROLE
     *
     * @mbggenerated Thu Mar 29 16:21:41 GMT+08:00 2012
     */
    List<SystemUsersRole> selectByExample(SystemUsersRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_USERS_ROLE
     *
     * @mbggenerated Thu Mar 29 16:21:41 GMT+08:00 2012
     */
    SystemUsersRole selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_USERS_ROLE
     *
     * @mbggenerated Thu Mar 29 16:21:41 GMT+08:00 2012
     */
    int updateByExampleSelective(@Param("record") SystemUsersRole record, @Param("example") SystemUsersRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_USERS_ROLE
     *
     * @mbggenerated Thu Mar 29 16:21:41 GMT+08:00 2012
     */
    int updateByExample(@Param("record") SystemUsersRole record, @Param("example") SystemUsersRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_USERS_ROLE
     *
     * @mbggenerated Thu Mar 29 16:21:41 GMT+08:00 2012
     */
    int updateByPrimaryKeySelective(SystemUsersRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_USERS_ROLE
     *
     * @mbggenerated Thu Mar 29 16:21:41 GMT+08:00 2012
     */
    int updateByPrimaryKey(SystemUsersRole record);
}