package com.test.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SystemUsersExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYSTEM_USERS
     *
     * @mbggenerated Thu Mar 29 08:38:23 GMT+08:00 2012
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYSTEM_USERS
     *
     * @mbggenerated Thu Mar 29 08:38:23 GMT+08:00 2012
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYSTEM_USERS
     *
     * @mbggenerated Thu Mar 29 08:38:23 GMT+08:00 2012
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_USERS
     *
     * @mbggenerated Thu Mar 29 08:38:23 GMT+08:00 2012
     */
    public SystemUsersExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_USERS
     *
     * @mbggenerated Thu Mar 29 08:38:23 GMT+08:00 2012
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_USERS
     *
     * @mbggenerated Thu Mar 29 08:38:23 GMT+08:00 2012
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_USERS
     *
     * @mbggenerated Thu Mar 29 08:38:23 GMT+08:00 2012
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_USERS
     *
     * @mbggenerated Thu Mar 29 08:38:23 GMT+08:00 2012
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_USERS
     *
     * @mbggenerated Thu Mar 29 08:38:23 GMT+08:00 2012
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_USERS
     *
     * @mbggenerated Thu Mar 29 08:38:23 GMT+08:00 2012
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_USERS
     *
     * @mbggenerated Thu Mar 29 08:38:23 GMT+08:00 2012
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_USERS
     *
     * @mbggenerated Thu Mar 29 08:38:23 GMT+08:00 2012
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_USERS
     *
     * @mbggenerated Thu Mar 29 08:38:23 GMT+08:00 2012
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_USERS
     *
     * @mbggenerated Thu Mar 29 08:38:23 GMT+08:00 2012
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SYSTEM_USERS
     *
     * @mbggenerated Thu Mar 29 08:38:23 GMT+08:00 2012
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("USERNAME is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("USERNAME is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("USERNAME =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("USERNAME <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("USERNAME >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("USERNAME >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("USERNAME <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("USERNAME <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("USERNAME like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("USERNAME not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("USERNAME in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("USERNAME not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("USERNAME between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("USERNAME not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("PASSWORD is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("PASSWORD is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("PASSWORD =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("PASSWORD <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("PASSWORD >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("PASSWORD >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("PASSWORD <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("PASSWORD <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("PASSWORD like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("PASSWORD not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("PASSWORD in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("PASSWORD not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("PASSWORD between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("PASSWORD not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andLevelsIsNull() {
            addCriterion("LEVELS is null");
            return (Criteria) this;
        }

        public Criteria andLevelsIsNotNull() {
            addCriterion("LEVELS is not null");
            return (Criteria) this;
        }

        public Criteria andLevelsEqualTo(BigDecimal value) {
            addCriterion("LEVELS =", value, "levels");
            return (Criteria) this;
        }

        public Criteria andLevelsNotEqualTo(BigDecimal value) {
            addCriterion("LEVELS <>", value, "levels");
            return (Criteria) this;
        }

        public Criteria andLevelsGreaterThan(BigDecimal value) {
            addCriterion("LEVELS >", value, "levels");
            return (Criteria) this;
        }

        public Criteria andLevelsGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("LEVELS >=", value, "levels");
            return (Criteria) this;
        }

        public Criteria andLevelsLessThan(BigDecimal value) {
            addCriterion("LEVELS <", value, "levels");
            return (Criteria) this;
        }

        public Criteria andLevelsLessThanOrEqualTo(BigDecimal value) {
            addCriterion("LEVELS <=", value, "levels");
            return (Criteria) this;
        }

        public Criteria andLevelsIn(List<BigDecimal> values) {
            addCriterion("LEVELS in", values, "levels");
            return (Criteria) this;
        }

        public Criteria andLevelsNotIn(List<BigDecimal> values) {
            addCriterion("LEVELS not in", values, "levels");
            return (Criteria) this;
        }

        public Criteria andLevelsBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LEVELS between", value1, value2, "levels");
            return (Criteria) this;
        }

        public Criteria andLevelsNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LEVELS not between", value1, value2, "levels");
            return (Criteria) this;
        }

        public Criteria andCertIsNull() {
            addCriterion("CERT is null");
            return (Criteria) this;
        }

        public Criteria andCertIsNotNull() {
            addCriterion("CERT is not null");
            return (Criteria) this;
        }

        public Criteria andCertEqualTo(BigDecimal value) {
            addCriterion("CERT =", value, "cert");
            return (Criteria) this;
        }

        public Criteria andCertNotEqualTo(BigDecimal value) {
            addCriterion("CERT <>", value, "cert");
            return (Criteria) this;
        }

        public Criteria andCertGreaterThan(BigDecimal value) {
            addCriterion("CERT >", value, "cert");
            return (Criteria) this;
        }

        public Criteria andCertGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CERT >=", value, "cert");
            return (Criteria) this;
        }

        public Criteria andCertLessThan(BigDecimal value) {
            addCriterion("CERT <", value, "cert");
            return (Criteria) this;
        }

        public Criteria andCertLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CERT <=", value, "cert");
            return (Criteria) this;
        }

        public Criteria andCertIn(List<BigDecimal> values) {
            addCriterion("CERT in", values, "cert");
            return (Criteria) this;
        }

        public Criteria andCertNotIn(List<BigDecimal> values) {
            addCriterion("CERT not in", values, "cert");
            return (Criteria) this;
        }

        public Criteria andCertBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CERT between", value1, value2, "cert");
            return (Criteria) this;
        }

        public Criteria andCertNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CERT not between", value1, value2, "cert");
            return (Criteria) this;
        }

        public Criteria andCertinfoIsNull() {
            addCriterion("CERTINFO is null");
            return (Criteria) this;
        }

        public Criteria andCertinfoIsNotNull() {
            addCriterion("CERTINFO is not null");
            return (Criteria) this;
        }

        public Criteria andCertinfoEqualTo(String value) {
            addCriterion("CERTINFO =", value, "certinfo");
            return (Criteria) this;
        }

        public Criteria andCertinfoNotEqualTo(String value) {
            addCriterion("CERTINFO <>", value, "certinfo");
            return (Criteria) this;
        }

        public Criteria andCertinfoGreaterThan(String value) {
            addCriterion("CERTINFO >", value, "certinfo");
            return (Criteria) this;
        }

        public Criteria andCertinfoGreaterThanOrEqualTo(String value) {
            addCriterion("CERTINFO >=", value, "certinfo");
            return (Criteria) this;
        }

        public Criteria andCertinfoLessThan(String value) {
            addCriterion("CERTINFO <", value, "certinfo");
            return (Criteria) this;
        }

        public Criteria andCertinfoLessThanOrEqualTo(String value) {
            addCriterion("CERTINFO <=", value, "certinfo");
            return (Criteria) this;
        }

        public Criteria andCertinfoLike(String value) {
            addCriterion("CERTINFO like", value, "certinfo");
            return (Criteria) this;
        }

        public Criteria andCertinfoNotLike(String value) {
            addCriterion("CERTINFO not like", value, "certinfo");
            return (Criteria) this;
        }

        public Criteria andCertinfoIn(List<String> values) {
            addCriterion("CERTINFO in", values, "certinfo");
            return (Criteria) this;
        }

        public Criteria andCertinfoNotIn(List<String> values) {
            addCriterion("CERTINFO not in", values, "certinfo");
            return (Criteria) this;
        }

        public Criteria andCertinfoBetween(String value1, String value2) {
            addCriterion("CERTINFO between", value1, value2, "certinfo");
            return (Criteria) this;
        }

        public Criteria andCertinfoNotBetween(String value1, String value2) {
            addCriterion("CERTINFO not between", value1, value2, "certinfo");
            return (Criteria) this;
        }

        public Criteria andCerttimeIsNull() {
            addCriterion("CERTTIME is null");
            return (Criteria) this;
        }

        public Criteria andCerttimeIsNotNull() {
            addCriterion("CERTTIME is not null");
            return (Criteria) this;
        }

        public Criteria andCerttimeEqualTo(Date value) {
            addCriterion("CERTTIME =", value, "certtime");
            return (Criteria) this;
        }

        public Criteria andCerttimeNotEqualTo(Date value) {
            addCriterion("CERTTIME <>", value, "certtime");
            return (Criteria) this;
        }

        public Criteria andCerttimeGreaterThan(Date value) {
            addCriterion("CERTTIME >", value, "certtime");
            return (Criteria) this;
        }

        public Criteria andCerttimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CERTTIME >=", value, "certtime");
            return (Criteria) this;
        }

        public Criteria andCerttimeLessThan(Date value) {
            addCriterion("CERTTIME <", value, "certtime");
            return (Criteria) this;
        }

        public Criteria andCerttimeLessThanOrEqualTo(Date value) {
            addCriterion("CERTTIME <=", value, "certtime");
            return (Criteria) this;
        }

        public Criteria andCerttimeIn(List<Date> values) {
            addCriterion("CERTTIME in", values, "certtime");
            return (Criteria) this;
        }

        public Criteria andCerttimeNotIn(List<Date> values) {
            addCriterion("CERTTIME not in", values, "certtime");
            return (Criteria) this;
        }

        public Criteria andCerttimeBetween(Date value1, Date value2) {
            addCriterion("CERTTIME between", value1, value2, "certtime");
            return (Criteria) this;
        }

        public Criteria andCerttimeNotBetween(Date value1, Date value2) {
            addCriterion("CERTTIME not between", value1, value2, "certtime");
            return (Criteria) this;
        }

        public Criteria andPopedommodelIsNull() {
            addCriterion("POPEDOMMODEL is null");
            return (Criteria) this;
        }

        public Criteria andPopedommodelIsNotNull() {
            addCriterion("POPEDOMMODEL is not null");
            return (Criteria) this;
        }

        public Criteria andPopedommodelEqualTo(BigDecimal value) {
            addCriterion("POPEDOMMODEL =", value, "popedommodel");
            return (Criteria) this;
        }

        public Criteria andPopedommodelNotEqualTo(BigDecimal value) {
            addCriterion("POPEDOMMODEL <>", value, "popedommodel");
            return (Criteria) this;
        }

        public Criteria andPopedommodelGreaterThan(BigDecimal value) {
            addCriterion("POPEDOMMODEL >", value, "popedommodel");
            return (Criteria) this;
        }

        public Criteria andPopedommodelGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("POPEDOMMODEL >=", value, "popedommodel");
            return (Criteria) this;
        }

        public Criteria andPopedommodelLessThan(BigDecimal value) {
            addCriterion("POPEDOMMODEL <", value, "popedommodel");
            return (Criteria) this;
        }

        public Criteria andPopedommodelLessThanOrEqualTo(BigDecimal value) {
            addCriterion("POPEDOMMODEL <=", value, "popedommodel");
            return (Criteria) this;
        }

        public Criteria andPopedommodelIn(List<BigDecimal> values) {
            addCriterion("POPEDOMMODEL in", values, "popedommodel");
            return (Criteria) this;
        }

        public Criteria andPopedommodelNotIn(List<BigDecimal> values) {
            addCriterion("POPEDOMMODEL not in", values, "popedommodel");
            return (Criteria) this;
        }

        public Criteria andPopedommodelBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("POPEDOMMODEL between", value1, value2, "popedommodel");
            return (Criteria) this;
        }

        public Criteria andPopedommodelNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("POPEDOMMODEL not between", value1, value2, "popedommodel");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("CREATETIME is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("CREATETIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("CREATETIME =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("CREATETIME <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("CREATETIME >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATETIME >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("CREATETIME <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATETIME <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("CREATETIME in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("CREATETIME not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("CREATETIME between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATETIME not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreateuserIsNull() {
            addCriterion("CREATEUSER is null");
            return (Criteria) this;
        }

        public Criteria andCreateuserIsNotNull() {
            addCriterion("CREATEUSER is not null");
            return (Criteria) this;
        }

        public Criteria andCreateuserEqualTo(String value) {
            addCriterion("CREATEUSER =", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotEqualTo(String value) {
            addCriterion("CREATEUSER <>", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserGreaterThan(String value) {
            addCriterion("CREATEUSER >", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserGreaterThanOrEqualTo(String value) {
            addCriterion("CREATEUSER >=", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserLessThan(String value) {
            addCriterion("CREATEUSER <", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserLessThanOrEqualTo(String value) {
            addCriterion("CREATEUSER <=", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserLike(String value) {
            addCriterion("CREATEUSER like", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotLike(String value) {
            addCriterion("CREATEUSER not like", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserIn(List<String> values) {
            addCriterion("CREATEUSER in", values, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotIn(List<String> values) {
            addCriterion("CREATEUSER not in", values, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserBetween(String value1, String value2) {
            addCriterion("CREATEUSER between", value1, value2, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotBetween(String value1, String value2) {
            addCriterion("CREATEUSER not between", value1, value2, "createuser");
            return (Criteria) this;
        }

        public Criteria andStsIsNull() {
            addCriterion("STS is null");
            return (Criteria) this;
        }

        public Criteria andStsIsNotNull() {
            addCriterion("STS is not null");
            return (Criteria) this;
        }

        public Criteria andStsEqualTo(BigDecimal value) {
            addCriterion("STS =", value, "sts");
            return (Criteria) this;
        }

        public Criteria andStsNotEqualTo(BigDecimal value) {
            addCriterion("STS <>", value, "sts");
            return (Criteria) this;
        }

        public Criteria andStsGreaterThan(BigDecimal value) {
            addCriterion("STS >", value, "sts");
            return (Criteria) this;
        }

        public Criteria andStsGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("STS >=", value, "sts");
            return (Criteria) this;
        }

        public Criteria andStsLessThan(BigDecimal value) {
            addCriterion("STS <", value, "sts");
            return (Criteria) this;
        }

        public Criteria andStsLessThanOrEqualTo(BigDecimal value) {
            addCriterion("STS <=", value, "sts");
            return (Criteria) this;
        }

        public Criteria andStsIn(List<BigDecimal> values) {
            addCriterion("STS in", values, "sts");
            return (Criteria) this;
        }

        public Criteria andStsNotIn(List<BigDecimal> values) {
            addCriterion("STS not in", values, "sts");
            return (Criteria) this;
        }

        public Criteria andStsBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("STS between", value1, value2, "sts");
            return (Criteria) this;
        }

        public Criteria andStsNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("STS not between", value1, value2, "sts");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SYSTEM_USERS
     *
     * @mbggenerated do_not_delete_during_merge Thu Mar 29 08:38:23 GMT+08:00 2012
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SYSTEM_USERS
     *
     * @mbggenerated Thu Mar 29 08:38:23 GMT+08:00 2012
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}