package com.test.entity;

import com.test.entity.SystemFieldPopedom;
import com.test.entity.SystemFieldPopedomExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SystemFieldPopedomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_FIELD_POPEDOM
     *
     * @mbggenerated Wed Mar 28 14:43:41 GMT+08:00 2012
     */
    int countByExample(SystemFieldPopedomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_FIELD_POPEDOM
     *
     * @mbggenerated Wed Mar 28 14:43:41 GMT+08:00 2012
     */
    int deleteByExample(SystemFieldPopedomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_FIELD_POPEDOM
     *
     * @mbggenerated Wed Mar 28 14:43:41 GMT+08:00 2012
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_FIELD_POPEDOM
     *
     * @mbggenerated Wed Mar 28 14:43:41 GMT+08:00 2012
     */
    int insert(SystemFieldPopedom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_FIELD_POPEDOM
     *
     * @mbggenerated Wed Mar 28 14:43:41 GMT+08:00 2012
     */
    int insertSelective(SystemFieldPopedom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_FIELD_POPEDOM
     *
     * @mbggenerated Wed Mar 28 14:43:41 GMT+08:00 2012
     */
    List<SystemFieldPopedom> selectByExample(SystemFieldPopedomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_FIELD_POPEDOM
     *
     * @mbggenerated Wed Mar 28 14:43:41 GMT+08:00 2012
     */
    SystemFieldPopedom selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_FIELD_POPEDOM
     *
     * @mbggenerated Wed Mar 28 14:43:41 GMT+08:00 2012
     */
    int updateByExampleSelective(@Param("record") SystemFieldPopedom record, @Param("example") SystemFieldPopedomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_FIELD_POPEDOM
     *
     * @mbggenerated Wed Mar 28 14:43:41 GMT+08:00 2012
     */
    int updateByExample(@Param("record") SystemFieldPopedom record, @Param("example") SystemFieldPopedomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_FIELD_POPEDOM
     *
     * @mbggenerated Wed Mar 28 14:43:41 GMT+08:00 2012
     */
    int updateByPrimaryKeySelective(SystemFieldPopedom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_FIELD_POPEDOM
     *
     * @mbggenerated Wed Mar 28 14:43:41 GMT+08:00 2012
     */
    int updateByPrimaryKey(SystemFieldPopedom record);
}