package com.test.entity;

import java.math.BigDecimal;
import java.util.Date;

public class SystemFieldPopedom {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_FIELD_POPEDOM.ID
     *
     * @mbggenerated Wed Mar 28 14:43:41 GMT+08:00 2012
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_FIELD_POPEDOM.cName
     *
     * @mbggenerated Wed Mar 28 14:43:41 GMT+08:00 2012
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_FIELD_POPEDOM.eName
     *
     * @mbggenerated Wed Mar 28 14:43:41 GMT+08:00 2012
     */
    private String ename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_FIELD_POPEDOM.tID
     *
     * @mbggenerated Wed Mar 28 14:43:41 GMT+08:00 2012
     */
    private String tid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_FIELD_POPEDOM.createTime
     *
     * @mbggenerated Wed Mar 28 14:43:41 GMT+08:00 2012
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_FIELD_POPEDOM.createUser
     *
     * @mbggenerated Wed Mar 28 14:43:41 GMT+08:00 2012
     */
    private String createuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_FIELD_POPEDOM.sts
     *
     * @mbggenerated Wed Mar 28 14:43:41 GMT+08:00 2012
     */
    private BigDecimal sts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_FIELD_POPEDOM.remark
     *
     * @mbggenerated Wed Mar 28 14:43:41 GMT+08:00 2012
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_FIELD_POPEDOM.ID
     *
     * @return the value of SYSTEM_FIELD_POPEDOM.ID
     *
     * @mbggenerated Wed Mar 28 14:43:41 GMT+08:00 2012
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_FIELD_POPEDOM.ID
     *
     * @param id the value for SYSTEM_FIELD_POPEDOM.ID
     *
     * @mbggenerated Wed Mar 28 14:43:41 GMT+08:00 2012
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_FIELD_POPEDOM.cName
     *
     * @return the value of SYSTEM_FIELD_POPEDOM.cName
     *
     * @mbggenerated Wed Mar 28 14:43:41 GMT+08:00 2012
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_FIELD_POPEDOM.cName
     *
     * @param cname the value for SYSTEM_FIELD_POPEDOM.cName
     *
     * @mbggenerated Wed Mar 28 14:43:41 GMT+08:00 2012
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_FIELD_POPEDOM.eName
     *
     * @return the value of SYSTEM_FIELD_POPEDOM.eName
     *
     * @mbggenerated Wed Mar 28 14:43:41 GMT+08:00 2012
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_FIELD_POPEDOM.eName
     *
     * @param ename the value for SYSTEM_FIELD_POPEDOM.eName
     *
     * @mbggenerated Wed Mar 28 14:43:41 GMT+08:00 2012
     */
    public void setEname(String ename) {
        this.ename = ename == null ? null : ename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_FIELD_POPEDOM.tID
     *
     * @return the value of SYSTEM_FIELD_POPEDOM.tID
     *
     * @mbggenerated Wed Mar 28 14:43:41 GMT+08:00 2012
     */
    public String getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_FIELD_POPEDOM.tID
     *
     * @param tid the value for SYSTEM_FIELD_POPEDOM.tID
     *
     * @mbggenerated Wed Mar 28 14:43:41 GMT+08:00 2012
     */
    public void setTid(String tid) {
        this.tid = tid == null ? null : tid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_FIELD_POPEDOM.createTime
     *
     * @return the value of SYSTEM_FIELD_POPEDOM.createTime
     *
     * @mbggenerated Wed Mar 28 14:43:41 GMT+08:00 2012
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_FIELD_POPEDOM.createTime
     *
     * @param createtime the value for SYSTEM_FIELD_POPEDOM.createTime
     *
     * @mbggenerated Wed Mar 28 14:43:41 GMT+08:00 2012
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_FIELD_POPEDOM.createUser
     *
     * @return the value of SYSTEM_FIELD_POPEDOM.createUser
     *
     * @mbggenerated Wed Mar 28 14:43:41 GMT+08:00 2012
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_FIELD_POPEDOM.createUser
     *
     * @param createuser the value for SYSTEM_FIELD_POPEDOM.createUser
     *
     * @mbggenerated Wed Mar 28 14:43:41 GMT+08:00 2012
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser == null ? null : createuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_FIELD_POPEDOM.sts
     *
     * @return the value of SYSTEM_FIELD_POPEDOM.sts
     *
     * @mbggenerated Wed Mar 28 14:43:41 GMT+08:00 2012
     */
    public BigDecimal getSts() {
        return sts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_FIELD_POPEDOM.sts
     *
     * @param sts the value for SYSTEM_FIELD_POPEDOM.sts
     *
     * @mbggenerated Wed Mar 28 14:43:41 GMT+08:00 2012
     */
    public void setSts(BigDecimal sts) {
        this.sts = sts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_FIELD_POPEDOM.remark
     *
     * @return the value of SYSTEM_FIELD_POPEDOM.remark
     *
     * @mbggenerated Wed Mar 28 14:43:41 GMT+08:00 2012
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_FIELD_POPEDOM.remark
     *
     * @param remark the value for SYSTEM_FIELD_POPEDOM.remark
     *
     * @mbggenerated Wed Mar 28 14:43:41 GMT+08:00 2012
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}